name: swagger
version: 1.0.0
description: Swagger API client
dependencies:
  base_code:
    path: ../
  http:
  flutter_localizations:
    sdk: flutter
  http_interceptor: ^1.0.2
  get_it: ^7.2.0
  flutter_secure_storage: ^9.2.4
  rxdart: ^0.27.2

dependency_overrides:
  intl: 0.18.0

environment:
  sdk: '>=3.0.0 <4.0.0'